### ISSUE TITLE
Adjust "to" date when "From" is changed to later

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/react-native-app#109]
When user sets "From" date to later than "To", a new request for list of hotels is immediately dispatched, which fails because interval "from-to" doesn't make any sense, e.g. "From Feb 2 to January 9".

**Comment by mrtnzlml** [comment]
Additional condition:

```
Object {
  "_proxy": Object {
    "statusCode": 1003,
    "url": "https://hotels-api.skypicker.com/api/hotels?output=hotel_details&radius=50&latitude=50.0755&longitude=14.4378&checkin=2018-01-08&checkout=2018-02-14&room1=A",
  },
  "locations": Array [
    Object {
      "column": 3,
      "line": 4,
    },
  ],
  "message": "bookings.getHotelAvailabilityV2: checkout date (2018-02-14) must be between 1 and 30 days after the checkin date (2018-01-08).",
  "path": Array [
    "allHotels",
  ],
}
```

**Comment by jakubzaba** [comment]
Note to myself:
- allow set TO date before FROM when you changing date, but show message about it
- show message when you set date range higher than 30 days
- disable past dates
- **KIS**, will be replaced with range date picker anyway

**Comment by jaroslav-kubicek** [comment]
What about simply adjusting the other date, just like in kiwi.com native app or Booking.com, e.g. If I set "To" to earlier date than "From", let's say January 25, "From" is automatically updated as well to "January 24"? UX should be much better with this.
