### ISSUE TITLE
Create children age pickers

### ISSUE THREAD

**Issue by jakubzaba** [kiwicom/react-native-app#130]
It is possible to open modal from modal, so new screen is not necessary as design suggests.
https://zpl.io/a8yKj46
<img width="353" alt="screen shot 2018-01-05 at 11 02 17 am" src="https://user-images.githubusercontent.com/1803950/34604405-ee7c69de-f207-11e7-8992-f322b3e34496.png">

**Comment by mrtnzlml** [comment]
What do you suggest here actually? Are you changing the design/UX?

**Comment by jakubzaba** [comment]
I stick with commonly used popup rather than new screen.
Open popup with adults, children -> increment children -> show list item -> click on list item -> show another popup with number picker.
I spoked with Martin about it and he agreed on it.

**Comment by mrtnzlml** [comment]
It still doesn't work. I cannot change child age after I selected and searched for the first time. Please fix it and provide appropriate tests. Thank you.
