### ISSUE TITLE
Make it possible to dismiss the Relay error

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/react-native-app#137]
Currently, when some data are missing, the error overlays the "book now" button:

<img src="https://user-images.githubusercontent.com/1473642/34678571-ced1f2d2-f493-11e7-894f-941d6072aaed.png" width=300>

I think the solution could look somehow like this:

![image](https://user-images.githubusercontent.com/1473642/34679112-3ad309ac-f495-11e7-89a2-4f351511fcb5.png)

**Comment by mrtnzlml** [comment]
What about the same/similar behavior as yellow warnings in RN itself to keep it simple? Meaning: dismiss it totally (until you get another error again).

**Comment by VaclavSir** [comment]
I think the solution I draw:
- Isn't much more difficult to develop
- Is more user friendly
- When someone reports an issue with a screenshot, we can see there was an error

But I'm OK with the simpler solution if it's easier to develop.
