### ISSUE TITLE
Hotels: show only first couple of facilities

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#145]
See: https://zpl.io/VkK8lo8

<img width="315" alt="screen shot 2018-01-09 at 20 48 14" src="https://user-images.githubusercontent.com/978368/34723816-714d15a6-f57e-11e7-82c1-c86156dede9a.png">

**Comment by VaclavSir** [comment]
Changed to show first 10 or 15 facilities (we'll see what amount will look better).
