### ISSUE TITLE
Hotels: "book now" button overlaps room's "select" button

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/react-native-app#147]
The "book now" button overlaps the last room's "select" button. Please, add some whitespace below the last room so that the book now button would not cover it.

![img_4640](https://user-images.githubusercontent.com/7661448/34726750-3366e18c-f555-11e7-9624-8bb5bb25a904.PNG)

**Comment by mrtnzlml** [comment]
Note: this will be probably solved by #144.

**Comment by mrtnzlml** [comment]
Fixed by #144
