### ISSUE TITLE
Add tags to hotels list

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/react-native-app#193]
Please, add these tags to the hotels list and enable filtering based on these tags:

Airport Shuttle
Family Rooms
Facilities for Disabled Guests
Fitness Center
Parking
Free Parking
Valet Parking
Indoor Pool
Pet Friendly
Spa
WiFi
Pet Friendly
No Credit Card Required
Free Cancellation

![snimek obrazovky 2018-01-17 v 16 13 09](https://user-images.githubusercontent.com/7661448/35049857-9ce990f8-fba1-11e7-94a4-a2d54e35dacd.png)

**Comment by jakubzaba** [comment]
Thanks for this list.
Now how about UX? Do we still want to put all these filters into stripe? I suggest to put there just a button "more filters" and show popup with all filters as checkboxes.

**Comment by MRTNKCR** [comment]
Well, well, well... This is exactly what I suggested during the design process. However, they want to keep this stripe since it's an important part of the new website they are preparing and they want the filtering to be the same across all platforms.... 😶

**Comment by jakubzaba** [comment]
Still in progress with Brno whether it'll be one button with checkboxes or bunch of button. Here's how it looks like in both cases https://drive.google.com/file/d/1lg_KE2DEgEwRK2oLBfgcXS3155Gf75D7/view

**Comment by jakubzaba** [comment]
```
No Credit Card Required
Free Cancellation
```
will be done in different issue/pr to deliver more often, smaller features. #203, #204
