### ISSUE TITLE
Distance from center filter

### ISSUE THREAD

**Issue by jakubzaba** [kiwicom/react-native-app#202]
Add distance from center filter

**Comment by jakubzaba** [comment]
We're missing this information in hotel results as well.

**Comment by mrtnzlml** [comment]
Any plans how to do this?

**Comment by jakubzaba** [comment]
I guess we can get hotels GPS and calculate distance with hotel's city GPS that we can get from location API.
But firstly we should take a look on Booking API if it does not provide this information directly in response.

**Comment by jakubzaba** [comment]
@MRTNKCR Here is what we have:
- there is actually no filter for `distance from center` on Booking neither in Booking API.
You can only display information about distance and you can sort by distance.
- Booking uses city center as an area (defined by polygon, but you cannot get that from API), so when you calculate e.g. 2km from gps of city center, it shows 650m from city center on Booking.

So...
1) If we still want to show distance information, how it should works? Similar to Booking - <1.5km is city center, the rest shows distance from city center (2km => 500m from city center)?
2) What about filter? Options are:
- don't do that, booking also don't have that filter
- do just sort, then we miss design
- do similar approach as price filter limits have. Pre-request hotels ordered by distance and filter out those that are farther than distance filter value - too bad, but could work.

**Comment by mrtnzlml** [comment]
What is the progress here?

**Comment by jakubzaba** [comment]
Didn't get answer yet. It must wait for Martin's return.
