### ISSUE TITLE
Hotels: refactor date pickers logic

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#214]
Date pickers are very broken - it's not possible to change the year and it resets dates. It's very hard to describe all weirdnesses around these date pickers:

![jan-25-2018 16-35-35](https://user-images.githubusercontent.com/978368/35381125-d5679004-01ed-11e8-92ad-26a428d4e6c6.gif)

I should call it - please fix random date generator... 😄

**Comment by tbergq** [comment]
This seems to be the default behavior of the UIDatepicker(ios component that is being rendered)
The onDateChange callback is not called before you click on the select date button. 

We need to find another datepicker component that does not use the native UIDatepicker if we want to fix this issue.

**Comment by mrtnzlml** [comment]
I cannot believe that native datepicker is totally broken. Please read this: https://github.com/kiwicom/react-native-app/pull/213#issuecomment-360381931

**Comment by mrtnzlml** [comment]
💩 UX - you cannot set past dates. It's not a bug as I thought.
