### ISSUE TITLE
Text of full screen image not completely visible on iPhone X

### ISSUE THREAD

**Issue by tbergq** [kiwicom/react-native-app#217]
![image uploaded from ios 1](https://user-images.githubusercontent.com/7705041/35442369-53da4ff8-02a7-11e8-8a6b-2d523ad74e88.jpg)

**Comment by mrtnzlml** [comment]
Protip: in simulator go File > New Screen Shot or Command+S (probably Ctrl+S).

**Comment by mrtnzlml** [comment]
resolved
