### ISSUE TITLE
Hotels: map is not zoomable or scrollable because of map markers

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#236]
See: https://drive.google.com/file/d/1qLqHU2ch6zPb-DeglvPjWmEvdobUJLa1/view

Not sure if we can fix it. Give it few hours and let me know the result. I know that Airbnb map is very broken so this may be quite complicated to fix.

**Comment by mrtnzlml** [comment]
Issue https://github.com/react-community/react-native-maps/issues/1539 needs to be resolved first. I do not consider this a big issue so closing for now.

**Comment by vemundeldegard** [comment]
I think this is a big issue...

**Comment by tbergq** [comment]
It seems to be working for us now atleast

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7705041/46127795-11590480-c232-11e8-8b07-591f3c7f7734.gif)

**Comment by maxencehenneron** [comment]
Did anything change?
