### ISSUE TITLE
Hotels: server error while trying to search hotels far in the future

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#237]
Steps to reproduce:

- go to hotels search
- change checkout date to something like 2022
- select date

Server returns "server error". Why? Also, I checked CloudWatch and it seems like our client is not sending correct date (year) to the server/Booking.com.

**Comment by tbergq** [comment]
Booking.com server returns error 400, it has a limitation of 360 days in the future for checkout date. 
The client sends the date correctly, I did console logs before fetch query, and it sends the date as expected.

I will add max date limitations to the datepickers.
