### ISSUE TITLE
Adjust datepicker colors (use Kiwi.com colors)

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#252]
We need to resolve colors anyway. Datepicker is working with system colors so we need to setup this in the native code. Please investigate if we can adjust the `shared/src/Color.js` implementation to use these native constants so we can eventually extract it into our new library (RN bridge).

**Comment by tbergq** [comment]
When the color constants are bridged we can easily add this to `sharted/src/Color.js` by adding
`...NativeModules.ColorManager.colors`

@mrtnzlml What should be done here before this has been bridged?

**Comment by mrtnzlml** [comment]
Ok, won't fix for now. We would be just adjusting the development environment to satisfy QA. Let's wait for the bridge...
