### ISSUE TITLE
Split view doesn't work with correct dimensions

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#278]
See: https://slack-files.com/T024Z3H2Y-F93TJECJX-c73e2d3cd4 (it should be responsive - change to mobile view). I tried to investigate a little bit few weeks ago but it seems like it's broken in RN: https://github.com/facebook/react-native/issues/16152

**Comment by tbergq** [comment]
@mrtnzlml What is going on here? I don't understand this video. I have no simulator where I can put safari next to my running app? AFAIK, my iPad can not do this either.

**Comment by mrtnzlml** [comment]
@tbergq It's this feature: https://support.apple.com/en-za/HT207582

We are currently not getting the right screen dimensions and for this reason, the application looks stupid in multitask mode (it's not responsive).

**Comment by mrtnzlml** [comment]
#301
