### ISSUE TITLE
Inconsistency in hotel room prices

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#283]
Steps to reproduce:

1. search hotels for 5 adults, you'll see hotel for let's say 1940 EUR
2. open this hotel

Now there are two situations:

- you are able to find a room with this price for 5 adults, in this case, everything is fine and you need to find another hotel:
- you'll be able to find cheaper rooms (usually for less than 5 adults)

Questions to answer:

- [ ] Why is there this inconsistency? Is it normal behavior of Booking.com? I can imagine an explanation where this is correct.
- [ ] Can we improve it somehow to prevent this confusion?
- [ ] Are we actually sending information about adults to the single hotel page? This needs verification.

---

Example 1: I found a hotel room for 5 adults and price 1010,32 but after opening the hotel - there is no such a room. However, there are two smaller rooms for 442,67 and 567,65 (1010,32 in total) so from my point of view, it works correctly.

Example 2: City "Zlín", hotel "Penzion Sokolská", two persons - price is 300 but there are even cheaper rooms for 2 adults. Why?

See: https://trello.com/c/fB6jWpxI/112-bug-inconsistency-in-prices-on-search-and-in-hotel-booking

**Comment by tbergq** [comment]
I checked the exact same dates from Example 2 on Booking.com. The price in the search result said 300 EUR, but the cheapest room was actually 228 EUR. 

I don't think we can do anything here? Can we register a bug with Booking.com?
