### ISSUE TITLE
Passing parameters to hotel search screen

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#299]
_copy-pasted from the specs (section Passing parameters to hotel search screen)_

Search results should be opened in one of following modes:

- for active booking (destination city coordinates should be provided)
- for explore destination and airport (destination city coordinates should be provided)
- for explore my surroundings (actual location coordinates should be provided)
- location unknown

Hotels search results screen should accept parameter with location (latitude + longitude). If such parameters are passed, results should be displayed for accordingly and search input text should be nearest city (city specified for nearest hotel). If no parameters are provided, hotel search dialog should be empty and wait for user input.

---

It's probably going to be necessary to do it in multiple PRs. Please. I don't know what changes are necessary at this moment.

**Comment by tbergq** [comment]
- [ ] `app/hotels/index.js` should take a coordinate prop with latitude and longitude floats and pass it to `AllHotelsSearch`
- [ ] `AllHotelsSearch` should take a coordinate prop and use it as the initial search query if present
- [ ] If no coordinate prop is passed it should wait for user input and do no query

I think these are the changes needed. Did I forget anything @mrtnzlml ?

**Comment by mrtnzlml** [comment]
> Did I forget anything?

I have no idea, it's quite complicated to imagine it like this for me.

**Comment by tbergq** [comment]
Sure, I get that, just checking if you had some more input. 

From what I can see, this is what we need to do.
