### ISSUE TITLE
Text: use custom font

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#307]
We need to distribute our own font to prevent these issues on weird devices: https://github.com/facebook/react-native/issues/15114

System fonts:
- iOS: SanFran
- Android: Roboto

Related issue: https://trello.com/c/sYuG1zzB/159-bug-uncompleted-strings-and-layouts-in-hotels

**Comment by tbergq** [comment]
@mrtnzlml this is just relevant for android right?

**Comment by mrtnzlml** [comment]
@tbergq Probably yes.

**Comment by tbergq** [comment]
Did a quick check on the kiwi app, deployment target is iOS 9, and font has been SanFran since iOS 9, i will leave the system fonts for iOS

**Comment by mrtnzlml** [comment]
@tbergq OK, it's reported only on weird Android devices. They use a custom font instead of Roboto and RN is not happy with this font for some reason.
