### ISSUE TITLE
Make the search form scrollable

### ISSUE THREAD

**Issue by tbergq** [kiwicom/react-native-app#329]
[Trello](https://trello.com/c/aJWCXQgn/164-make-the-search-form-scrollable)

**Comment by mrtnzlml** [comment]
Already fixed. Please do not create issues without reason.

**Comment by mrtnzlml** [comment]
Haha, reopening because of performance issues.

**Comment by mrtnzlml** [comment]
https://github.com/kiwicom/react-native-app/pull/339
