### ISSUE TITLE
Date pickers are not optimized for small devices

### ISSUE THREAD

**Issue by tbergq** [kiwicom/react-native-app#330]
[Trello](https://trello.com/c/TYCGDaYg/129-bug-date-pickers-are-not-optimized-for-small-devices)

**Comment by mrtnzlml** [comment]
@tbergq Do you need this issue?

**Comment by tbergq** [comment]
I like to actually know what we are working on, since I can't see it in Trello.

**Comment by mrtnzlml** [comment]
Alright. It's huge pain in the ass for me to handle multiple issues for one problem (there are even 5 duplicated issues for some problems 🙄). But I understand...
