### ISSUE TITLE
Gallery - Size change

### ISSUE THREAD

**Issue by tbergq** [kiwicom/react-native-app#345]
[Trello](https://trello.com/c/FuRRnBka/198-bug-gallery-size-change)

**Comment by mrtnzlml** [comment]
@tbergq Basically, this line is wrong: https://github.com/kiwicom/react-native-app/blob/master/app/hotels/src/gallery/GalleryGrid.js#L56

**Comment by tbergq** [comment]
Yes, I know, @mrtnzlml, I see no better way than adding this to `Device`

```
/**
   * Should only be used in componentDidMount
   */
  getDimensions() {
    return renewDimensions();
  },
```

And use that

**Comment by mrtnzlml** [comment]
I think this approach is valid but only for Android devices, because there is no multitasking like on iOS (only that's broken actually).
