### ISSUE TITLE
Single hotel page

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#40]
Please create single hotel page structure with basic components (Relay container, visual components for header, description, rooms, ...). This issue is not about design but about proper components structure (you'll design it properly later).

~For this, you'll need this MR `chatbot/kiwi-chatbot-infrastructure!538`. In case the MR will not be merged yet please use mock data.~

zpl://screen?sid=5a1edf0356c752b71a613634&pid=5a1308cdae8ae89cae5c15af

**Comment by VaclavSir** [comment]
Until "Hotel detail fields" issue in our GraphQL gets resolved, I'm mocking the data.

**Comment by mrtnzlml** [comment]
Not completely done but I will create new tasks since the description of issues doesn't work very well and we have different direction now...
