### ISSUE TITLE
Not all needed fonts for Android are packaged into react-native-app-hotels NPM package

### ISSUE THREAD

**Issue by Blackhex** [kiwicom/react-native-app#425]
There are only the following fonts in the Android version of react-native-app-hotels NPM package:
 - Roboto-Regular.ttf
 - SFPProText-Semibold.ttf
 - spfont.ttf

When kiwi.com Android application is packaged with only that fonts, some font icons are broken. When the application is manually packaged with all fonts listed here https://github.com/kiwicom/react-native-app/tree/master/android/app/src/main/assets/fonts the icons are fine but I do not know which fonts are really needed an which are not.

Please, add all the needed fonts to the NPM package. 

BTW: kiwi.com Android application uses only Roboto-Regular for the texts and spfont for the icon fonts. Any other font should not bee needed.

**Comment by mrtnzlml** [comment]
@Blackhex What icons are broken?

**Comment by gerak-cz** [comment]
![device-2018-03-27-122243](https://user-images.githubusercontent.com/10685840/37961876-bdc03ec8-31b9-11e8-814f-2f7f5b60ee0c.png)

This is just main screen. There are broken icons on other screens as well.

**Comment by mrtnzlml** [comment]
Did you install `react-native-vector-icons` package correctly?

**Comment by tbergq** [comment]
https://github.com/oblador/react-native-vector-icons#user-content-installation

**Comment by Blackhex** [comment]
I have tried several ways how to package with react-native-vector-icons library including putting lines suggested in the documentation into the kiwi.com Android application project but fonts are still not packaged into the APK.

Anyway, how difficult would be for you to include those font files into the react-native-app-hotels NPM package?

**Comment by Blackhex** [comment]
And which fonts from the react-native-vector-icons project are really used?

**Comment by mrtnzlml** [comment]
We use only material design icons from this package but we do not use this font directly so you'll have to follow their installation guide. There is nothing to fix on our side, right @tbergq?

**Comment by tbergq** [comment]
I will check it in `react-native-app-connected` to confirm, but I think not.

**Comment by Blackhex** [comment]
I have found a different solution how to include font assets, thank you anyway.

**Comment by mrtnzlml** [comment]
@Blackhex Can you please share with us your solution?

**Comment by Blackhex** [comment]
I have created a wrapper gradle project that adds Android assets packaging and Maven deployment to react-native-vector-icons Android project and then hooked a new task before mergeAssets stage that copies the fonts to the wrapper project's assets folder.
