### ISSUE TITLE
Hotels: price filter works with wrong currency

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#450]
Check the price filter vs. returned prices. If I remember correctly the price filter works only with EURs and therefore the correct label should be "1263 EUR" in all cases. Please verify if I am correct.

![image uploaded from ios](https://user-images.githubusercontent.com/978368/38259024-4c6e3fb2-3764-11e8-9fcd-364a09fbc433.png)

**Comment by tbergq** [comment]
Yes, you are right, though this is not a good user experience. I would like to have a function (from native 🙈 ) that transforms from users currency to EUR, so we can query with EUR and show the filter in the users selected currency

For now, we will solve this by replacing with EUR
