### ISSUE TITLE
Add build version into ancillaries logging

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/react-native-app#464]
Currently, we use something like `kiwi-ios-react` label. The new format should contain even the version so for example `kiwi-ios-react-0.0.18`. The easiest solution is probably to require `package.json` directly... (Because hey! We are in JS! 🙂)

Alternative inspiration: https://github.com/facebook/react-native/blob/v0.55.2/Libraries/Core/ReactNativeVersion.js

**Comment by tbergq** [comment]
The current interface looks like 
```
RCT_EXPORT_METHOD(ancillaryDisplayed:(NSString *)type) {
    [self.logger ancillaryDisplayed:type];
}

RCT_EXPORT_METHOD(ancillaryPurchased:(NSString *)type) {
    [self.logger ancillaryPurchased:type];
}
```

So, there are 2 options 
- Native developers add the version they get from hotels `package.json` in the native code 
- They expand the method to take label/version

**Comment by tbergq** [comment]
🙈  Oh, I though it was related to the logging module

**Comment by mrtnzlml** [comment]
Yeah, sorry - the "logging" word in the title is not very smart. They are actually logging it (well Booking.com is) but for us, it's just a label. Keep it simple... :)
