### ISSUE TITLE
Find a way how to inject credentials & secrets

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/react-native-app#51]
We need a find way how to seamlessly inject secrets into our app, without necessity to move the whole repo away from public github repo.

It's required e.g. for map to make it work on Android: https://docs.expo.io/versions/latest/sdk/map-view.html#deploying-to-a-standalone-app-on-android

**Comment by mrtnzlml** [comment]
https://github.com/kiwicom/react-native-app/issues/23
