### ISSUE TITLE
Format price & currency according to used locale

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/react-native-app#55]
As mentioned in PR #49 , price and currency should be always formatted according to user's locale settings.

 ### Things to do

- format price based on passed locale settings
- create new general purpose text component what will take care of that formatting (and probably accept styles as prop to make it possible to work inside various components)

**Comment by mrtnzlml** [comment]
But we don't know how to do it properly yet. And moreover, nobody said to do so (we will maybe use the same simplification as Airbnb)... I would personally prefer to create just `Price` component to wrap all prices and implement the "before/after logic" later if needed.
